# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6df86195c32a3d3eb80a273eff07aa96"
name = "cash-on-delivery-app-v1"
application_url = "https://diane-finger-issued-prison.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nitishtestv1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://diane-finger-issued-prison.trycloudflare.com/auth/callback",
  "https://diane-finger-issued-prison.trycloudflare.com/auth/shopify/callback",
  "https://diane-finger-issued-prison.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
