# This file stores configurations for your Shopify app.

scopes = "read_content,read_metaobject_definitions,read_metaobjects,read_orders,read_themes,write_content,write_metaobject_definitions,write_metaobjects,write_orders,write_products,write_themes"
